### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by scalda** [dries007/MCLink_Mod#1]
Hi,

I am receiving crashes on clean server running the 1.12.2 and then a 1.10.2 custom mod pack on there respective latest forge/MC versions Please find the attached crash reports

[1.12.2](https://pastebin.com/yw981xTJ)
[1.10.2](https://pastebin.com/h6ZF4P2z)

Regards

scalda

**Comment by dries007** [comment]
`See log above for more info.` The actual error is a `[FATAL]` error line in the log, usually in the +- 10 lines above the start of the `---- Minecraft Crash Report ----` line, in a box made out of `-=##=-`, to make it obvious.

These crashes are intentional, they indicate one of the following scenarios:
1. `Your MCLink config is empty, this will result in no-one being allowed on the server!`
2. `Your tokenConfig for MCLink contains some services that are not available.`
2. `Your tokenConfig for MCLink contains some API tokens that are invalid.`

**Comment by scalda** [comment]
Ok thanks, perhaps this info needs putting somewhere, as you need to load the server at least once to get the config to generate, so if it's going to crash it s gonna confuse alot of people like it has me to be able to get this to run. But thanks for the help.

**Comment by dries007** [comment]
It sais it right there in the log file though. I don't understand why people think it's easier look online for answers when all the info is right here.
But I'll probably make it clearer.

**Comment by scalda** [comment]
Yeah sorry I didn't even think to look in the actual forge log file from
that line comment
