### ISSUE TITLE
Support 1.14 clients for linking accounts

### ISSUE THREAD

**Issue by JLyne** [dries007/MCLink_Mod#18]
Requesting as per the readme comment.

Currently using mclink on a few 1.14.2 servers, plugin works fine.
However, the linking server doesn't appear to support 1.14 clients currently ("Unknown protocol version").

Naturally, telling everyone to launch 1.13 to link instead is a bit awkward, so support for 1.14 clients would be appreciated. Thanks.

**Comment by dries007** [comment]
It's in progress, the underlying library didn't yet get updated last time I checked, and I'm in the middle of exams now. If I manage to scrape together an hour or so I can update it, but only after the underlying library pushes an update. If I have to so that too, it takes a lot longer.
See barneygale/quarry#59

**Comment by dries007** [comment]
This has been fixed for a while, sorry for not closing this issue.
