### ISSUE TITLE
McLink suddenly stopped letting people in :(

### ISSUE THREAD

**Issue by PureLove-X** [dries007/MCLink_Mod#19]
McLink suddenly stopped letting people in- I tried resetting the api key- That didn't work- I'm not sure what's going on :/ 

Here's our api key:
sD5WUULyMDVFgYCfvAQHLIZjWZd1A5fA

**Comment by dries007** [comment]
If this happens there is a 90% chance it's the API key's owner's (streamer's) link between MCLink and Twitch has been broken for some reason. (This is an ongoing issue, it can happen to anyone, but it's hard to pin down due to it not being reproducable when testing.)

The solution is to have the owner(streamer) log into the authentication server and complete the Twitch link again.

Please re-open if this was not the issue! (If it was, a comment would be nice so I know it's fixed.)
