### ISSUE TITLE
Time Period?

### ISSUE THREAD

**Issue by danmartinez78** [dries007/MCLink_Mod#23]
Is there a time period associated with the authentication?

If a user stops subbing on Twitch do they get removed from the whitelist?
For Patreon, if a user has donated above the minimum amount, do they have access forever?

**Comment by dries007** [comment]
For Patreon it looks at the monthly pledge amount. Once they stop their pledge, it expires.
The access stays for up to a day or two, because some of the API data is cached and not updated instantly.

Same goes for Twitch. As soon as the sub does not show up on the Twitch API anymore, access is denied again. (With maybe a small grace period, depening on the API and some caching.)

**Comment by danmartinez78** [comment]
Question answered fully, closing.
